package com.dlm.modelo.negocio;
// Generated 26 juin 2018 17:51:50 by Hibernate Tools 5.2.3.Final

/**
 * Person generated by hbm2java
 */
public class Person implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String personName;
	private Integer personAge;

	public Person() {
	}

	public Person(String personName) {
		this.personName = personName;
	}

	public Person(String personName, Integer personAge) {
		this.personName = personName;
		this.personAge = personAge;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getPersonName() {
		return this.personName;
	}

	public void setPersonName(String personName) {
		this.personName = personName;
	}

	public Integer getPersonAge() {
		return this.personAge;
	}

	public void setPersonAge(Integer personAge) {
		this.personAge = personAge;
	}

}
